version: '3.8'
networks:
  app-network:
    driver: bridge
services:
  app:
    build: .
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  db:
    image: postgres
    networks:
      - app-network
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - "54321:5432"
  artillery:
    image: artilleryio/artillery:latest
    network_mode: host
    ports:
      - "8081:8080"
    volumes:
      - ./internal/tests/artillery:/app
    command: run /app/test.yml